server {
    listen 80;
    
    # เสิร์ฟไฟล์จากโฟลเดอร์นี้
    root /usr/share/nginx/html;
    index index.html index.htm;

    # สำหรับ React Router ให้จับทุก Path ไปที่ index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
