version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: celora_mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - ./LoRa.alerts.json:/docker-entrypoint-initdb.d/LoRa.alerts.json:ro
      - ./LoRa.device_data.json:/docker-entrypoint-initdb.d/LoRa.device_data.json:ro
      - ./LoRa.devices.json:/docker-entrypoint-initdb.d/LoRa.devices.json:ro
      - ./LoRa.elders.json:/docker-entrypoint-initdb.d/LoRa.elders.json:ro
      - ./LoRa.users.json:/docker-entrypoint-initdb.d/LoRa.users.json:ro
      - ./LoRa.zones.json:/docker-entrypoint-initdb.d/LoRa.zones.json:ro
    restart: always

  backend:
    build: 
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: celora_backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/LoRa
      - JWT_SECRET=xx12345ce
    depends_on:
      - mongodb
    restart: always 

  frontend:
    build: 
      context: ./FrontEnd
      dockerfile: Dockerfile
    container_name: celora_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always